version: 0.2

env:
  variables:
    terraform_version: "0.11.7"
    s3_bucket: "get-chofu-city-gabage-skill-tsubauaaa-s3"
phases:
  install:
    commands:
      - cd /tmp && aws s3 cp s3://${s3_bucket}/terraform_${terraform_version}_linux_amd64.zip ./terraform.zip && unzip terraform.zip && mv terraform /usr/bin
  pre_build:
    commands:
      - cd ${CODEBUILD_SRC_DIR}/src
      - zip -X -J -r GetChofuCityGabageSkill.zip . -x '*.tf' '*pyc'
      - terraform init -backend-config bucket=${s3_bucket}
      - terraform plan -var-file=terraform.tfvars -var aws_account_id=`aws sts get-caller-identity --query 'Account' --output text`
  build:
    commands:
      - aws s3 sync ../files s3://${s3_bucket}/garbage_calender
      - terraform apply -auto-approve -var-file=terraform.tfvars -var aws_account_id=`aws sts get-caller-identity --query 'Account' --output text`
  post_build:
    commands:
      - echo Build completed on `date`
